[project]
name = "spryker-doc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "dotenv>=0.9.9",
    "ollama-python>=0.1.2",
    "requests>=2.32.3",
]
